name: "Deploy"

on: # This workflow must be triggered on one condition only
  workflow_dispatch: # when we ask it manually (through the Actions UI or the GitHub API)

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs: #this section contains the tasks / jobs that must be executed
  update_server:
    runs-on: "ubuntu-latest" # this job must run on a Ubuntu container
    environment: production
    steps:
      - name: checkout on main
        uses: actions/checkout@main # action that make a checkout on the main branch
        with:
          ref: ${{ github.read_ref }}

      - id: release
        uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: patch
          use_github_release_notes: true
          tag_prefix: v

      - name: "NodeJS setup"
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Make sure that pokemon-showdown dependency is up-to-date
        run: npm update pokemon-showdown

      - name: Change version into package.json
        run: >
          sed -i 's/"version": ".*"/"version": "${{ steps.release.outputs.version }}"/g' package.json

      - name: Bump version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[VERSION] Bump to ${{ steps.release.outputs.version }}"
          commit_user_name: GitHub Actions Bot
          commit_author: GitHub Action <actions@github.com>
          skip_dirty_check: false

      - name: Setup SSH connection
        run: >
          echo "${{ secrets.PRIVATE_KEY }}" > ./private_key && chmod 600 ./private_key &&
          echo '#!/bin/sh' >> ./passphrase_script.sh &&
          echo "echo ${{ secrets.PASSPHRASE }}" >> ./passphrase_script.sh &&
          chmod +x ./passphrase_script.sh

      - run: ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      - run: DISPLAY=1 SSH_ASKPASS="./passphrase_script.sh" ssh-add ./private_key < /dev/null

      - name: "Update remote"
        run: >
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} -o StrictHostKeyChecking=no
          "cd ${{ secrets.REMOTE_PATH }}/ && 
           git fetch &&
           git reset --hard origin/main && npm ci"
