name: Workflow to allow MR on main
on:
  pull_request:
    branches:
      - main

jobs:
  job-running-tests:
    env:
      LAST_GEN: 8
    runs-on: ubuntu-latest
    container: node:12

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: pokemon-showdown local repository setup
        run: npm run clone-showdown

      - name: Start tests
        run: npm run test
