name: "Update production environment"

on: # This workflow must be triggered on one condition only
  workflow_dispatch: # when we ask it manually (through the Actions UI or the GitHub API)

jobs: #this section contains the tasks / jobs that must be executed
  update_server:
    runs-on: "ubuntu-latest" # this job must run on a Ubuntu container
    steps:
      - name: checkout on main
        uses: actions/checkout@main # action that make a checkout on the main branch
        with:
          ref: ${{ github.read_ref }}

      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_release: minor
          tag_prefix: v

      - name: Change version into package.json
        run: 'sed -i s/"version": ".*"/"version": "${{ steps.release.outputs.version }}"/g package.json'

      - name: Bump version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[VERSION] Bump to ${{ steps.release.outputs.version }}"
          commit_user_name: GitHub Actions Bot
          commit_author: GitHub Action <actions@github.com>
          skip_dirty_check: false

      - name: "Update remote"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ${{ secrets.REMOTE_DIR }}/dataprovider
            git pull https://ii02735:${{ secrets.GITHUB_TOKEN }}/ii02735/dataprovider-pokemon-showdown master
