name: "Sync with pokemon-showdown"


on: # This workflow must be triggered on two conditions
        workflow_dispatch: # when we ask it manually (through the Actions UI or the GitHub API)

        push: # when we make a push to the main branch
            branches:
              - main

jobs: #this section contains the tasks / jobs that must be executed
        sync: # the job name
                runs-on: 'ubuntu-latest' # this job must run on a Ubuntu container
                steps:
                        - name: checkout on main
                          uses: actions/checkout@main # action that make a checkout on the main branch
                          with:
                             ref: ${{ github.read_ref }}
                             
                        - name: "generate JSON"
                          uses: actions/setup-node@v2
                          with:
                            node-version: '12'
                        - run: git clone https://github.com/smogon/pokemon-showdown.git
                        - run: git clone https://github.com/ii02735/Smogon-Stats-Viewer.git
                        - run: npm run build
                        - name: Commit differences # commit if differences are tracked after updates (previous step)
                          uses: stefanzweifel/git-auto-commit-action@v4
                          with:
                              commit_message: Synchronization with pokemon-showdown
                              commit_user_name: GitHub Actions Bot
                              commit_author: GitHub Action <actions@github.com>
                              skip_dirty_check: false
                              push_options:  --force
        json_files:
                needs: [sync]
                runs-on: 'ubuntu-latest' # this job must run on a Ubuntu container
                steps:
                  - name: checkout on main
                    uses: actions/checkout@main # action that make a checkout on the main branch
                    with:
                       ref: ${{ github.read_ref }}
                  
                  - name: "Send all JSON files"
                    uses: appleboy/scp-action@master
                    with:
                      host: ${{ secrets.HOST }}
                      port: ${{ secrets.PORT }}
                      username: ${{ secrets.USERNAME }}
                      key: ${{ secrets.PRIVATE_KEY }}
                      passphrase: ${{ secrets.PASSPHRASE }}
                      source: "json/abilities.json,json/items.json,json/learns.json,json/moves.json,json/natures.json,json/pokemons.json,json/pokemonTier.json,json/types.json"
                      target: ${{ secrets.REMOTE_DIR }}/public

