name: "Sync submodule"


on: # This workflow must be triggered on two conditions
        workflow_dispatch: # when we ask it manually (through the Actions UI or the GitHub API)

        push: # when we make a push to the main branch
            branches:
              - main

jobs: #this section contains the tasks / jobs that must be executed
        sync: # the job name
                runs-on: 'ubuntu-latest' # this job must run on a Ubuntu container
                steps:
                        - name: checkout on main
                          uses: actions/checkout@main # action that make a checkout on the main branch
                          with:
                             ref: ${{ github.read_ref }}

                        - name: update submodule content # fetch the latest updates and apply them to the submodule
                          uses: textbook/git-checkout-submodule-action@master
                          with:
                              remote: true

                        - name: "generate JSON"
                          uses: actions/setup-node@v2
                          with:
                            node-version: '12'
                        - run: npm run build && npm run postbuild
                        - name: Commit differences # commit if differences are tracked after updates (previous step)
                          uses: stefanzweifel/git-auto-commit-action@v4
                          with:
                              commit_message: Synchronization with submodule
                              commit_user_name: GitHub Actions Bot
                              commit_author: GitHub Action <actions@github.com>
                              skip_dirty_check: false
                              push_options:  --force

