name: "Update databases from JSON changes"
on:
  push:
    branches: main
    paths:
      - "json/*.json"
      - "usages/**/*.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare ssh connection
        run: sudo apt-get install sshpass

      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2 # will create filters for changed files
        id: filter-json-data
        with:
          filters: >
            tags:
              - 'json/tags.json'
            tiers:
              - 'json/tiers.json'
            natures:
              - 'json/natures.json'
            types:
              - 'json/types.json'
            abilities:
              - 'json/abilities.json'
            items:
              - 'json/items.json'
            moves:
              - 'json/moves.json'
            pokemon:
              - 'json/pokemons.json'
            learns:
              - 'json/learns.json'
            pokemon_tiers:
              - 'json/pokemonTier.json'
            usages:
              - 'usages/**/*.json'
            guide_tags:
             - 'json/guide_tags.json'

      - name: Update tags
        if: steps.filter-json-data.outputs.tags == 'true'
        run: >
          sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no 
          "cd ${{ secrets.REMOTE_PATH }}/dataprovider &&
          DB_HOST=${{ secrets.DB_HOST }} node14 db/importTags.js"

      - name: Update guide tags
        if: steps.filter-json-data.outputs.guide_tags == 'true'
        run: >
          sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no 
          "cd ${{ secrets.REMOTE_PATH }}/dataprovider &&
          DB_HOST=${{ secrets.DB_HOST }} node14 db/importGuideTags.js"

      - name: Update tiers
        if: steps.filter-json-data.outputs.tiers == 'true'
        run: >
          sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no 
          "cd ${{ secrets.REMOTE_PATH }}/dataprovider &&
          DB_HOST=${{ secrets.DB_HOST }} node14 db/importTiers.js"

      - name: Update natures
        if: steps.filter-json-data.outputs.natures == 'true'
        run: >
          sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no 
          "cd ${{ secrets.REMOTE_PATH }}/dataprovider &&
          DB_HOST=${{ secrets.DB_HOST }} node14 db/importNatures.js"

      - name: Update types
        if: steps.filter-json-data.outputs.types == 'true'
        run: >
          sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no 
          "cd ${{ secrets.REMOTE_PATH }}/dataprovider &&
          DB_HOST=${{ secrets.DB_HOST }} node14 db/importTypes.js"

      - name: Update abilities
        if: steps.filter-json-data.outputs.abilities == 'true'
        run: >
          sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no 
          "cd ${{ secrets.REMOTE_PATH }}/dataprovider &&
          DB_HOST=${{ secrets.DB_HOST }} node14 db/importAbilities.js"

      - name: Update items
        if: steps.filter-json-data.outputs.items == 'true'
        run: >
          sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no 
          "cd ${{ secrets.REMOTE_PATH }}/dataprovider &&
          DB_HOST=${{ secrets.DB_HOST }} node14 db/importItems.js"

      - name: Update moves
        if: steps.filter-json-data.outputs.moves == 'true'
        run: >
          sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no 
          "cd ${{ secrets.REMOTE_PATH }}/dataprovider &&
          DB_HOST=${{ secrets.DB_HOST }} node14 db/importMoves.js"

      - name: Update pokemons
        if: steps.filter-json-data.outputs.pokemon == 'true'
        run: >
          sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no 
          "cd ${{ secrets.REMOTE_PATH }}/dataprovider &&
          DB_HOST=${{ secrets.DB_HOST }} node14 db/importPokemon.js"

      #- name: Update learns
      #  if: steps.filter-json-data.outputs.learns == 'true'
      #  run: >
      #    sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no 
      #    "cd ${{ secrets.REMOTE_PATH }}/dataprovider &&
      #    DB_HOST=${{ secrets.TEST_DB_HOST }} node14 db/importPokemonMoves.js &&
      #    DB_HOST=${{ secrets.DB_HOST }} node14 db/importPokemonMoves.js"

      - name: Update pokemon tiers
        if: steps.filter-json-data.outputs.pokemon_tiers == 'true'
        run: >
          sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no 
          "cd ${{ secrets.REMOTE_PATH }}/dataprovider &&
          DB_HOST=${{ secrets.DB_HOST }} node14 db/importPokemonTiers.js"

      - name: Update usages
        if: steps.filter-json-data.outputs.usages == 'true'
        run: >
          sshpass -p "${{ secrets.PASSWORD }}" ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} -p ${{ secrets.PORT }} -o StrictHostKeyChecking=no 
          "cd ${{ secrets.REMOTE_PATH }}/dataprovider &&
          DB_HOST=${{ secrets.DB_HOST }} node14 db/importUsages.js &&
          DB_HOST=${{ secrets.DB_HOST }} node14 db/importUsagesVGC.js"
