name: "Update JSON files in repository"

on: # This workflow must be triggered on two conditions
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: # when we ask it manually (through the Actions UI or the GitHub API)

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs: #this section contains the tasks / jobs that must be executed
  update_json_files: # the job name
    runs-on: "ubuntu-latest" # this job must run on a Ubuntu container
    env:
      LAST_GEN: 8
    steps:
      - name: set timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Paris"
      - name: checkout on main
        uses: actions/checkout@main # action that makes a checkout
        with:
          ref: ${{ github.read_ref }} # will checkout on th desired branch

      - name: "generate JSON"
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - run: npm ci && npm run clone-showdown
      - run: USAGE_PATH='usages' npm run generate-stats
      - name: Commit differences # commit if differences are tracked after updates (previous step)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "JSON files updated"
          commit_user_name: GitHub Actions Bot
          commit_author: GitHub Action <actions@github.com>
          skip_dirty_check: false

      - name: "Push JSON to repository to trigger database update"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: git push https://ii02735:${{ secrets.GITHUB_TOKEN }}@github.com/ii02735/dataprovider-pokemon-showdown.git main

      - name: Setup SSH connection
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: >
          echo "${{ secrets.PRIVATE_KEY }}" > ./private_key && chmod 600 ./private_key &&
          echo '#!/bin/sh' >> ./passphrase_script.sh &&
          echo "echo ${{ secrets.PASSPHRASE }}" >> ./passphrase_script.sh &&
          chmod +x ./passphrase_script.sh

      - if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: ssh-agent -a $SSH_AUTH_SOCK > /dev/null

      - if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: DISPLAY=1 SSH_ASKPASS="./passphrase_script.sh" ssh-add ./private_key < /dev/null

      - name: "Update remote"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: >
          ssh -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} -o StrictHostKeyChecking=no
          "cd ${{ secrets.REMOTE_PATH }}/ && 
           git pull https://ii02735:${{ secrets.GITHUB_TOKEN }}@github.com/ii02735/dataprovider-pokemon-showdown.git main"
